import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Activity, ThumbsDown, ThumbsUp } from "lucide-react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/Card";

function DailyFeedback({ feedbacks }: { feedbacks: Array<{ type: "UP" | "DOWN"; createdAt: string }> }) {
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const key = date.toISOString().slice(0, 10); const values = feedbacks.filter((feedback) => feedback.createdAt.slice(0, 10) === key); return { key, label: `${date.getDate()}.${String(date.getMonth() + 1).padStart(2, "0")}`, up: values.filter((value) => value.type === "UP").length, down: values.filter((value) => value.type === "DOWN").length }; }), [feedbacks]);
  const max = Math.max(1, ...days.flatMap((day) => [day.up, day.down]));
  return <div className="mt-5"><div className="flex h-36 items-end gap-2 border-b border-ink-700/40 pb-2">{days.map((day) => <div key={day.key} className="flex-1 min-w-0 h-full flex items-end justify-center gap-1"><span className="w-2 rounded-t bg-success" style={{ height: `${Math.max(3, (day.up / max) * 100)}%` }} title={`👍 ${day.up}`} /><span className="w-2 rounded-t bg-danger" style={{ height: `${Math.max(3, (day.down / max) * 100)}%` }} title={`👎 ${day.down}`} /></div>)}</div><div className="grid grid-cols-7 gap-2 mt-2 text-[10px] text-center text-ink-500">{days.map((day) => <span key={day.key}>{day.label}</span>)}</div></div>;
}

export function Statistics() {
  const providersQuery = useQuery({ queryKey: ["feedback", "provider-stats"], queryFn: api.getProviderStats });
  const modelsQuery = useQuery({ queryKey: ["models"], queryFn: api.getModels });
  const links = Object.values(modelsQuery.data?.categories ?? {}).flatMap((models) => models.flatMap((model) => model.providerModels.map((providerModel) => ({ id: providerModel.id, label: `${model.name} · ${providerModel.provider.name}` }))));
  const [selectedId, setSelectedId] = useState<string>(""); const activeId = selectedId || links[0]?.id || "";
  const feedbackQuery = useQuery({ queryKey: ["feedback", activeId], queryFn: () => api.getFeedback(activeId), enabled: Boolean(activeId) });
  const providers = providersQuery.data?.providers ?? [];
  return <div className="pt-24 pb-16 px-4 max-w-7xl mx-auto"><div className="mb-8"><h1 className="text-display font-medium text-ink-100">Статистика</h1><p className="text-sm text-ink-400 mt-2">Личный feedback и надёжность связок provider/model. Звёзды ролей не меняются.</p></div><Card padding="md" className="mb-6"><div className="flex flex-wrap gap-3 justify-between"><div><h2 className="text-sm font-medium text-ink-100">Feedback модели</h2><p className="text-xs text-ink-500 mt-1">Зелёный — 👍, красный — 👎, по дням.</p></div><select value={activeId} onChange={(event) => setSelectedId(event.target.value)} className="h-9 max-w-full rounded-lg bg-ink-800/60 border border-ink-700/40 px-2 text-xs text-ink-100">{links.map((link) => <option key={link.id} value={link.id}>{link.label}</option>)}</select></div>{activeId ? <><DailyFeedback feedbacks={feedbackQuery.data?.feedbacks ?? []} /><p className="mt-3 text-xs text-ink-400">Всего: <span className="text-success">👍 {feedbackQuery.data?.up ?? 0}</span> · <span className="text-danger">👎 {feedbackQuery.data?.down ?? 0}</span></p></> : <p className="mt-5 text-sm text-ink-500">Добавьте модель в рейтинг, чтобы появилась её статистика.</p>}</Card><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{providers.map((provider) => <Card key={provider.id} padding="md"><div className="flex justify-between gap-3"><div><h2 className="text-sm font-medium text-ink-100">{provider.name}</h2><p className="text-xs text-ink-500 mt-1">{provider.online}/{provider.total} Working</p></div><span className={provider.reliability >= 80 ? "text-success text-sm" : "text-warning text-sm"}>{provider.reliability}%</span></div><div className="mt-5 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-ink-800/50 p-2"><Activity className="h-4 w-4 mx-auto text-accent mb-1" />{provider.failed}<br /><span className="text-ink-500">Failed</span></div><div className="rounded-lg bg-ink-800/50 p-2"><ThumbsUp className="h-4 w-4 mx-auto text-success mb-1" />{provider.up}<br /><span className="text-ink-500">Up</span></div><div className="rounded-lg bg-ink-800/50 p-2"><ThumbsDown className="h-4 w-4 mx-auto text-danger mb-1" />{provider.down}<br /><span className="text-ink-500">Down</span></div></div></Card>)}{!providersQuery.isLoading && !providers.length && <p className="text-sm text-ink-500">Пока нет данных для статистики.</p>}</section></div>;
}
